# VacationPy
----

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os
import json

# Import API key
from api_keys import g_key

print(g_key)

AIzaSyDVg6EPzJchta3rYrvzc8ACFvMmyjSrglo

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#Read in the city and weather data from WeatherPy
cities_data_to_load = "output_data/cities.csv"
cities_weather_df = pd.read_csv(cities_data_to_load)
cities_weather_df = pd.DataFrame(cities_weather_df)
cities_weather_df['City']=cities_weather_df['City'].str.capitalize()
cities_weather_df['Country']=cities_weather_df['Country'].str.upper()
cities_weather_df

,City ID,City,Country,Act Lat,Act Lon,Temperature (F),Humidity,Cloudiness,Wind Speed
0,212730,Kisangani,CD,0.52,25.20,75.42,75,61,3.67
1,1501377,Kungurtug,RU,50.60,97.52,27.77,58,0,4.23
2,2163355,Hobart,AU,-42.88,147.33,40.64,87,0,9.17
3,3652764,Puerto ayora,EC,-0.74,-90.35,84.13,70,20,9.17
4,3137469,Sorland,NO,67.67,12.69,37.40,86,20,12.75
...,...,...,...,...,...,...,...,...,...
496,361058,Alexandria,EG,31.22,29.96,61.21,67,8,8.05
497,1218612,Murgab,TM,37.50,61.97,39.20,86,90,6.93
498,2038080,Chengzihe,CN,45.33,131.07,33.01,86,95,6.49
499,3356832,Henties bay,NA,-22.12,14.28,60.01,91,19,4.00
500,1511057,Bakchar,RU,57.02,82.07,29.73,91,16,12.15

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
#Configure gmaps and read api key
gmaps.configure(api_key=g_key)

#Grab teh needed columns for the humidity-weighted heatmap
city_humidity_map_data = cities_weather_df[['Act Lat', 'Act Lon', 'Humidity']]

#Center on Minneapolis!
minneapolis = [44.9778, -93.265]

#Set locations based on city lat long from WeatherPy
locations = city_humidity_map_data[['Act Lat', 'Act Lon']]

#Weight the heatmap by humidity level
weights = city_humidity_map_data['Humidity']

#Generate gmaps figure, add heatmap layer
fig = gmaps.figure(map_type='HYBRID', center = minneapolis, zoom_level=2)
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights, dissipating=False, max_intensity=100, point_radius=1.5))
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
#Set desired vacation parameters
ideal_temp = 80
ideal_humid = 45
ideal_wind = 100
ideal_clouds = 100

#user_inputs_df = pd.DataFrame('Temperature (F)': ideal_temp)
user_inputs_df = pd.DataFrame({'Temperature':[ideal_temp], 'Humidity':[ideal_humid], 'Wind':[ideal_wind], 'Clouds':[ideal_clouds]})

#Assume +/-10F and +/-10% humidity are acceptable tolerance levels to ideal
temp_tolerance = 10 
humid_tolerance = 10
upper_temp = ideal_temp+temp_tolerance
lower_temp = ideal_temp-temp_tolerance
upper_humid = ideal_humid+humid_tolerance
lower_humid = ideal_humid-humid_tolerance

#Select cities that meet the vacation criteria. Assume wind and cloudiness preferences represent maximums
cities_choice_df = cities_weather_df.loc[cities_weather_df['Temperature (F)']<=upper_temp]
cities_choice_df = cities_choice_df.loc[cities_choice_df['Temperature (F)']>=lower_temp]
cities_choice_df = cities_choice_df.loc[cities_choice_df['Humidity']<=upper_humid]
cities_choice_df = cities_choice_df.loc[cities_choice_df['Humidity']>=lower_humid]
cities_choice_df = cities_choice_df.loc[cities_choice_df['Wind Speed']<=ideal_wind]
cities_choice_df = cities_choice_df.loc[cities_choice_df['Cloudiness']<=ideal_clouds]

num_cities = cities_choice_df['City ID'].count()

#Summarize the criteria and number of cities selected
print(f'{num_cities} cities are in range of your criteria.')

#if after applying the criteria the number of cities is >10 then choose 10 randomly to limit API calls to Google Places
if num_cities>10:
    cities_choice_df = cities_choice_df.sample(10)
    print(f'We have randomly selected 10 cities.')

#Summarize
user_inputs_df.index = ['Vacation City Criteria']
print(user_inputs_df)
cities_choice_df.head(20)

20 cities are in range of your criteria.
We have randomly selected 10 cities.
                        Temperature  Humidity  Wind  Clouds
Vacation City Criteria           80        45   100     100

,City ID,City,Country,Act Lat,Act Lon,Temperature (F),Humidity,Cloudiness,Wind Speed
177,239899,Bria,CF,6.54,21.99,79.21,55,52,1.14
417,3353383,Rundu,NA,-17.93,19.77,73.24,40,49,3.20
114,3557758,Guane,CU,22.20,-84.09,89.46,47,0,3.27
449,4281897,Winfield,US,37.24,-97.00,85.01,39,1,11.41
19,3454783,Patos de minas,BR,-18.58,-46.52,80.76,55,51,2.64
215,187585,Marsabit,KE,2.33,37.99,73.56,46,58,13.91
131,3533462,Acapulco,MX,16.86,-99.89,86.00,48,40,5.82
50,3896218,Castro,CL,-42.47,-73.77,73.40,35,0,4.70
254,3995236,Mulege,MX,26.88,-111.98,73.00,45,100,3.91
342,3869716,Tocopilla,CL,-22.09,-70.20,83.34,37,27,6.82

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = cities_choice_df

params = {
    "radius": 5000,
    "type": "hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Act Lat"]
    lng = row["Act Lon"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params).json()
    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = response['results'][1]['name']
        hotel_df.loc[index, "Hotel Address"] = response['results'][1]['vicinity']
        hotel_df.loc[index, "Hotel Lat"] = response['results'][1]['geometry']['location']['lat']
        hotel_df.loc[index, "Hotel Lon"] = response['results'][1]['geometry']['location']['lng']
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

hotel_df

,City ID,City,Country,Act Lat,Act Lon,Temperature (F),Humidity,Cloudiness,Wind Speed,Hotel Name,Hotel Address,Hotel Lat,Hotel Lon
177,239899,Bria,CF,6.54,21.99,79.21,55,52,1.14,Forage d'eau_Pharmacie,"Base pharma, Bria",6.541566,21.992021
417,3353383,Rundu,NA,-17.93,19.77,73.24,40,49,3.20,Shoprite Rundu,Rundu Shopping Mall Cnr Maria Mwengere & Eugen...,-17.916151,19.769613
114,3557758,Guane,CU,22.20,-84.09,89.46,47,0,3.27,CUPET GUANE,Guane,22.203540,-84.086551
449,4281897,Winfield,US,37.24,-97.00,85.01,39,1,11.41,KSWC-FM Winfield,Winfield,37.245860,-96.971147
19,3454783,Patos de minas,BR,-18.58,-46.52,80.76,55,51,2.64,AdministraÃ§Ã£o do EstÃ¡dio Zama Maciel-Adezma,"Rua Joaquim das Chagas, 688 - VÃ¡rzea, Patos de...",-18.596874,-46.520968
215,187585,Marsabit,KE,2.33,37.99,73.56,46,58,13.91,Marsabit District Hospital,Marsabit,2.323733,37.991007
131,3533462,Acapulco,MX,16.86,-99.89,86.00,48,40,5.82,HS Hotsson Smart Acapulco,"Avenida Costera Miguel AlemÃ¡n 1803, Fraccionam...",16.860203,-99.873826
50,3896218,Castro,CL,-42.47,-73.77,73.40,35,0,4.70,Hotel Esmeralda,"Esmeralda 266, Castro, Castro",-42.483368,-73.763571
254,3995236,Mulege,MX,26.88,-111.98,73.00,45,100,3.91,Casa Granada,"No.1 Estero de Mulege S/N, Colonia, Heroica Mu...",26.898967,-111.959908
342,3869716,Tocopilla,CL,-22.09,-70.20,83.34,37,27,6.82,Hotel Galvarino,"21 de Mayo 2182, Tocopilla",-22.089458,-70.196096

In [8]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Lat", "Hotel Lon"]]

# Add marker layer ontop of heat map
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))